// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: action.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_StartTopology         ActionType = 0
	ActionType_StopTopology          ActionType = 1
	ActionType_StartInstallChaincode ActionType = 2
	ActionType_StartAttack           ActionType = 3
	ActionType_StartConsensus        ActionType = 4
	ActionType_StopConsensus         ActionType = 5
	ActionType_WaitTopologyRemove    ActionType = 6
	ActionType_StartClient           ActionType = 7
	ActionType_StartServer           ActionType = 8
	ActionType_InitOsmd              ActionType = 9
	ActionType_StartOsmd             ActionType = 10
	ActionType_StartRetrieveAcks     ActionType = 11
	ActionType_ChangeCorruptRatio    ActionType = 12
	ActionType_ModifyBloomFilter     ActionType = 13
	ActionType_ResultHandling        ActionType = 14
	ActionType_ClearKernelLog        ActionType = 15
	ActionType_RemoveKernelModule    ActionType = 16
	ActionType_InstallKernelModule   ActionType = 17
	ActionType_DoNothing             ActionType = 18
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0:  "StartTopology",
		1:  "StopTopology",
		2:  "StartInstallChaincode",
		3:  "StartAttack",
		4:  "StartConsensus",
		5:  "StopConsensus",
		6:  "WaitTopologyRemove",
		7:  "StartClient",
		8:  "StartServer",
		9:  "InitOsmd",
		10: "StartOsmd",
		11: "StartRetrieveAcks",
		12: "ChangeCorruptRatio",
		13: "ModifyBloomFilter",
		14: "ResultHandling",
		15: "ClearKernelLog",
		16: "RemoveKernelModule",
		17: "InstallKernelModule",
		18: "DoNothing",
	}
	ActionType_value = map[string]int32{
		"StartTopology":         0,
		"StopTopology":          1,
		"StartInstallChaincode": 2,
		"StartAttack":           3,
		"StartConsensus":        4,
		"StopConsensus":         5,
		"WaitTopologyRemove":    6,
		"StartClient":           7,
		"StartServer":           8,
		"InitOsmd":              9,
		"StartOsmd":             10,
		"StartRetrieveAcks":     11,
		"ChangeCorruptRatio":    12,
		"ModifyBloomFilter":     13,
		"ResultHandling":        14,
		"ClearKernelLog":        15,
		"RemoveKernelModule":    16,
		"InstallKernelModule":   17,
		"DoNothing":             18,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_action_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_action_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_action_proto_rawDescGZIP(), []int{0}
}

var File_action_proto protoreflect.FileDescriptor

const file_action_proto_rawDesc = "" +
	"\n" +
	"\faction.proto*\x89\x03\n" +
	"\n" +
	"ActionType\x12\x11\n" +
	"\rStartTopology\x10\x00\x12\x10\n" +
	"\fStopTopology\x10\x01\x12\x19\n" +
	"\x15StartInstallChaincode\x10\x02\x12\x0f\n" +
	"\vStartAttack\x10\x03\x12\x12\n" +
	"\x0eStartConsensus\x10\x04\x12\x11\n" +
	"\rStopConsensus\x10\x05\x12\x16\n" +
	"\x12WaitTopologyRemove\x10\x06\x12\x0f\n" +
	"\vStartClient\x10\a\x12\x0f\n" +
	"\vStartServer\x10\b\x12\f\n" +
	"\bInitOsmd\x10\t\x12\r\n" +
	"\tStartOsmd\x10\n" +
	"\x12\x15\n" +
	"\x11StartRetrieveAcks\x10\v\x12\x16\n" +
	"\x12ChangeCorruptRatio\x10\f\x12\x15\n" +
	"\x11ModifyBloomFilter\x10\r\x12\x12\n" +
	"\x0eResultHandling\x10\x0e\x12\x12\n" +
	"\x0eClearKernelLog\x10\x0f\x12\x16\n" +
	"\x12RemoveKernelModule\x10\x10\x12\x17\n" +
	"\x13InstallKernelModule\x10\x11\x12\r\n" +
	"\tDoNothing\x10\x12B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_action_proto_rawDescOnce sync.Once
	file_action_proto_rawDescData []byte
)

func file_action_proto_rawDescGZIP() []byte {
	file_action_proto_rawDescOnce.Do(func() {
		file_action_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_proto_rawDesc), len(file_action_proto_rawDesc)))
	})
	return file_action_proto_rawDescData
}

var file_action_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_action_proto_goTypes = []any{
	(ActionType)(0), // 0: ActionType
}
var file_action_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_action_proto_init() }
func file_action_proto_init() {
	if File_action_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_proto_rawDesc), len(file_action_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_proto_goTypes,
		DependencyIndexes: file_action_proto_depIdxs,
		EnumInfos:         file_action_proto_enumTypes,
	}.Build()
	File_action_proto = out.File
	file_action_proto_goTypes = nil
	file_action_proto_depIdxs = nil
}
