// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.28.2
// source: rate_adjust_mode.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateAdjustMode int32

const (
	RateAdjustMode_Epoch     RateAdjustMode = 0
	RateAdjustMode_Timestamp RateAdjustMode = 1
)

// Enum value maps for RateAdjustMode.
var (
	RateAdjustMode_name = map[int32]string{
		0: "Epoch",
		1: "Timestamp",
	}
	RateAdjustMode_value = map[string]int32{
		"Epoch":     0,
		"Timestamp": 1,
	}
)

func (x RateAdjustMode) Enum() *RateAdjustMode {
	p := new(RateAdjustMode)
	*p = x
	return p
}

func (x RateAdjustMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RateAdjustMode) Descriptor() protoreflect.EnumDescriptor {
	return file_rate_adjust_mode_proto_enumTypes[0].Descriptor()
}

func (RateAdjustMode) Type() protoreflect.EnumType {
	return &file_rate_adjust_mode_proto_enumTypes[0]
}

func (x RateAdjustMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RateAdjustMode.Descriptor instead.
func (RateAdjustMode) EnumDescriptor() ([]byte, []int) {
	return file_rate_adjust_mode_proto_rawDescGZIP(), []int{0}
}

var File_rate_adjust_mode_proto protoreflect.FileDescriptor

const file_rate_adjust_mode_proto_rawDesc = "" +
	"\n" +
	"\x16rate_adjust_mode.proto**\n" +
	"\x0eRateAdjustMode\x12\t\n" +
	"\x05Epoch\x10\x00\x12\r\n" +
	"\tTimestamp\x10\x01B\n" +
	"Z\b../typesb\x06proto3"

var (
	file_rate_adjust_mode_proto_rawDescOnce sync.Once
	file_rate_adjust_mode_proto_rawDescData []byte
)

func file_rate_adjust_mode_proto_rawDescGZIP() []byte {
	file_rate_adjust_mode_proto_rawDescOnce.Do(func() {
		file_rate_adjust_mode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rate_adjust_mode_proto_rawDesc), len(file_rate_adjust_mode_proto_rawDesc)))
	})
	return file_rate_adjust_mode_proto_rawDescData
}

var file_rate_adjust_mode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rate_adjust_mode_proto_goTypes = []any{
	(RateAdjustMode)(0), // 0: RateAdjustMode
}
var file_rate_adjust_mode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rate_adjust_mode_proto_init() }
func file_rate_adjust_mode_proto_init() {
	if File_rate_adjust_mode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rate_adjust_mode_proto_rawDesc), len(file_rate_adjust_mode_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rate_adjust_mode_proto_goTypes,
		DependencyIndexes: file_rate_adjust_mode_proto_depIdxs,
		EnumInfos:         file_rate_adjust_mode_proto_enumTypes,
	}.Build()
	File_rate_adjust_mode_proto = out.File
	file_rate_adjust_mode_proto_goTypes = nil
	file_rate_adjust_mode_proto_depIdxs = nil
}
