network_config:
  backend_addr: "10.134.86.26"
  backend_port: 8080
  validation_node_port: 9000

attack_config:
  thread_count: 40
  type: "udp flood attack"

path_config:
  cmd: "/home/zhf/Projects/emulator/backend/cmd"
  configuration_yml: "/home/zhf/Projects/emulator/backend/resources/configuration.yml"
  resources_path: "../resources"

url_config:
  start_topology_url: "startTopology"
  stop_topology_url: "stopTopology"
  start_attack_url: "startAttack"
  start_tx_rate_test_url: "startTxRateTest"
  stop_tx_rate_test_url: "stopTxRateTest"
  install_chain_code_url: "installChannelAndChaincode"

consensus_config:
  thread_count: 20

sec_path_mab_config:
  number_of_hops: 3
  number_of_intermediate_nodes: 4
  low_corrupt_ratio: 5000
  high_corrupt_ratio: 5000
