syntax = "proto3";

option go_package = "../types";

enum ActionType {
  StartTopology = 0;
  StopTopology = 1;
  StartInstallChaincode = 2;
  StartAttack = 3;
  StartConsensus = 4;
  StopConsensus = 5;
  WaitTopologyRemove = 6;
  WaitExperimentFinish = 7;
  StartClient = 8;
  StartServer = 9;
  InitOsmd = 10;
  StartOsmd = 11;
  StartRetrieveAcks = 12;
  ChangeCorruptRatio = 13;
  ModifyBloomFilter = 14;
  ResultHandling = 15;
  ClearKernelLog = 16;
  RemoveKernelModule = 17;
  InstallKernelModule = 18;
  SynchronizeTimestamp = 19;
  DoNothing = 20;
}